### ISSUE TITLE
Mute player

### ISSUE THREAD

**Issue by Behoston** [MultiChat/Development#10]
Why you don't add `/mute` command ;__;?

I really need this feature.

**Comment by OllieMartin** [comment]
Hey!

The reason MultiChat doesn't feature a mute command is because its in my opinion something which should be handled by your bans/punishments plugin. This is because muting someone is a way of dealing with players who cause issues. So it makes much more sense for a ban suite such as BungeeAdminTools to handle /ban, /mute, /kick etc.

(That is a great plugin by the way if you want a bungeecord enabled ban/mute solution etc.!)

That said, I have been considering developing a mute command for MultiChat as I am aware its not always featured in ban suites. So I will see what I can do regarding version 2.0 for you :)

Hope that helps!
