### ISSUE TITLE
Fetching prefix and nicknames

### ISSUE THREAD

**Issue by der71** [MultiChat/Development#13]
I'm trying to have all nicknames synced across the servers while fetching the prefixes from every servers.
To my understanding if I want to fetch the prefixes, I would install multichat in the plugins server from every server, but it also fetches the nicknames which then aren't synced anymore between servers.

To solve this there would either be a way to only fetch the prefixes or having multichat nicknames synced on the spigot server side with an mysql database for example.

I am using:
PermissionsEX 1.23.4 To give all the players prefixes according to there rank.
Multichat on bungee 1.5 To have a global chat between all servers.
Multichat on every server 1.5 Only to fetch the prefixes.....
Bungee Display Name 1.29.5 To have all the nicknames synced.
Vault 1.5.6
Spigot 1.12 (git-spigot-7228328-11323bf)
Bungeecord 1.12 (Snapshot-6958943:1245)

Are there others ways to solve this? I would like to keep using PEX.
Thanks in advance 

der71

**Comment by OllieMartin** [comment]
Hi there,
---
I am currently making an effort to sort out all the old issues reported with the plugin. Most of these are very old so will be marked as closed. If you still use the plugin and it is a valid error on the latest versions, then please open a new issue or get in touch with me. Thank you.
---

Unfortunately MultiChat nicknames are not currently synced across servers. They act as a drop in replacement for something like "essentialsX" nicknames features. This was a per server command. In future versions I will be adding an option for a "global" nickname command.

This will solve this issue :)

Apologies for the awful response time, I am making a point of going through all these old issues. I took a long break from the plugin which is why they went un-answered, but I have done a lot more work on it recently and am about to release a new version (1.6).

Best Regards,
Oliver
