### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by JSingDreams** [MultiChat/Development#15]
I am using PEX and I am set to the Owner rank which has all permissions, but for some reason, I can't use MultiChat commands. I tried adding a single permission node to a rank, but the player still couldn't use the command. I've got it to where it has our prefixes though.

**Comment by OllieMartin** [comment]
Hi there,
---
I am currently making an effort to sort out all the old issues reported with the plugin. Most of these are very old so will be marked as closed. They are being answered now for anyone else who has the issue to see the answer, even if it no longer is of importance to you. If you still use the plugin and it is a valid error on the latest versions, then please open a new issue or get in touch with me. Thank you.
---

This is because PEX cannot be used to assign _BungeeCord_ permissions. You need to do it in the BungeeCord config.yml or get a bungeecord specific permissions plugin :)

Apologies for the awful response time, I have been doing a lot of work on the plugin lately, and as part of that I am reviewing all the old issues.

Best Regards,
Oliver
