### ISSUE TITLE
[1.12.2]I can't mute a player

### ISSUE THREAD

**Issue by OldKingisdie** [MultiChat/Development#29]
I can't mute a player

**Comment by OllieMartin** [comment]
Hi there,
I am going to need some more information in order to provide any useful help. But taking a guess, the following points may be useful to you:

1. What plugin is providing your /mute command? If it is a spigot plugin like Essentials then it is not compatible with MultiChat because MultiChat is a Bungeecord plugin. You will need a bungeecord solution such as BungeeAdminTools, or enable the built in /mute command from MultiChat, this is in the ChatControl config file.
2. If the above doesn't help then please let me know the version of MultiChat you are using, what version of spigot/bukkit/sponge/paper you are using. As well as of course what plugin is providing your mute command.

I hope that helps!

**Comment by OldKingisdie** [comment]
Sponge version
My mute command from Nucleus plugin(https://nucleuspowered.org/)
And I don't found any admin or staff command can mute a player from wiki maybe I need a BungeeAdminTools

Finaly Could you support Itemchat plugin (https://ore.spongepowered.org/pie_flavor/ItemChat)

**Comment by OllieMartin** [comment]
Hi,
Nucleus is a sponge plugin, which hence will not be able to mute players from using bungeecord chat.
To fix this you have a couple of options. MultiChat has a built in mute command you can enable in the chat control config file, this allows you to mute players and control what types of chat they can use etc. (The wiki is still pending update to version 1.6 where this was added) Or you can get a whole bungeecord ban management plugin like BungeeAdminTools.

As for supporting things like chat item, that is something I’m working on :)

Hope that helps, any other issues just let me know!
