### ISSUE TITLE
Spaces in Prefixes

### ISSUE THREAD

**Issue by dukedase** [MultiChat/Development#5]
Hi!  For some reason since the newest update my groups in Luck Perms have an issue in /mc chat.  Their normal prefix is &f<&dGrand Duke&f> &d" and it works, however when they talk in /mc it shows as &f<&dGrand &aDuke&f> &d"

Also when I give people perms it doesn't seem to work.  Everyone who had perms before the update work fine, but now if I give someone "multichat.staff.admin" they can't use /ac.  Same thing happening with /spy.

**Comment by OllieMartin** [comment]
How odd! I shall investigate for you :)

**Comment by dukedase** [comment]
I am also getting this in the BungeeCord console when people talk:
https://i.gyazo.com/f9cfb8fac6c4d1238841a832f2d8757b.png

It is a visible lag in-game, though not horrible, it is only roughly 0.2 seconds delay.

**Comment by dukedase** [comment]
Ok, one more issue to add, this one is actually pretty important...

When I have someone in a primary group and a temporary parent group, it ONLY displays their primary prefix.  The parent group has a higher weight and higher weight prefix, so it should show that.  But it doesn't.

I asked Luck from LuckPerms about it and he says it is MultiChat causing it.  Is there any estimation for when these can be fixed as I wanted to go live today (We have been working on this server for almost two months)

**Comment by OllieMartin** [comment]
Okay sorry that you've got these issues. Could I please have a copy of your multichat config file just to double check some things. And could you let me know what versions of Luckperms you are using and if it is the bungeecord version or the spigot one or the sponge one etc. That way I can try and replicate the issues. I am pretty sure the issue with giving people permissions is not MultiChat as all my plugin does is simply check if someone has a permission, but I will double check in case. The lag on people talking Im not too sure about either, I don't think its a bug in the code as I have never seen it before on any of the servers running MultiChat, but once again I will check to see if I can spot anything :) Im guessing it must be some outside reason though to do with bungee itself or the computer hosting the server etc. As for the LuckPerms thing, I will try and replicate the issue, but as I said earlier in this message I need to know some Luckperms version information to try and see what I can do. MultiChat uses vault to get peoples displaynames, prefixes, suffixes etc, rather than hooking directly into Luckperms, so if Luckperms isnt updating the vault entries when you add a temporary parent group this could be the issue. That isnt something Id be able to fix though and Luck would have to do so.

Im not sure I can give you a date when I can fix it by as I am really busy with university at the moment but I will certainly try my best to fix as many issues as I can.

**Comment by dukedase** [comment]
I attached the bungee config, and v.2.17.73 for LP.  I will try doing exactly what I am doing here on another server (on the same machine, everything) without multichat and see if it happens.  I'll respond back when I know


[MultiChat.zip](https://github.com/MultiChat/Development/files/842466/MultiChat.zip)

**Comment by dukedase** [comment]
Ok, my testing says that it isn't Multichat, as I do not have it installed on the Test server.  So it is either EssentialsX, LuckPerms or something else.

Sorry for being a doodoo head about the time thing, it's just I have spent so much time and effort setting the server up and was ready to release it today only to have one of the last things I was testing go wrong lol

I'll report back if I find the issue

**Comment by dukedase** [comment]
I have another bug, chat colors don't work sometimes.  Multichat seems to stop the permission from being looked at.  When I use /lp verbose and have someone do &55 it doesn't even check.  When I go on my test server (Still using same plugins other than MC and the same SQL database) it works perfectly fine.

**Comment by OllieMartin** [comment]
For the prefix thing with the colours messing up, I can sort of see whats happening as your last bracket before the display name is &a, so somehow multichat is confusing itself and using that for the next word instead. I think I never really noticed as most plugins Ive used dont actually allow spaces in prefixes! Ill see if I can find a fix for this, but obviously a quick fix for you (while not ideal) would to be do [GrandDuke] without the space!

Im going to set up a test server later on today with the luckperms version installed etc, and I will try and figure out whats going on. Ill also go and look at their code as I had to do once before to see whats causing the issue! I still reckon they aren't updating vault with the temporary prefix because all multichat does is simply query vault for someones current prefix each time they chat, but you never know, I could have done something stupid (probably more likely to be honest!).

The permission thing again seems really weird as all multichat does is use the player.hasPermission() command when someone does something, so theres not much that can go wrong with it! But again Ill try and see what I can find 

Ill get back to you as soon as I know anything.

Oh and there is a pre-release of MultiChat 1.4.1 here: https://github.com/MultiChat/Development/blob/master/multichat/target/multichat-1.4.1.jar

Maybe try it out just in case it happens to fix anything! :) (Unlikely but it has been known to happen!)

**Comment by dukedase** [comment]
I've 'fixed' the issue with the spaces in prefix by just adding another color code after the space

The only issue that I am really concerned about is it not showing temporary parent prefixes.  The others aren't really something I can't live with.

**Comment by OllieMartin** [comment]
Hey,

Sorry for taking a while, Im still looking into the issues but am struggling to find any problems. :/ Im yet to delve into the Luckperms code to see if I can spot anything there but I will keep you updated.

**Comment by dukedase** [comment]
https://i.gyazo.com/76498b44007c33edac5fbb89ae95233c.png

Shows that Caligvla's primary group is grand_duke and she is currently getting permissions from Legatus, which has a higher weight and the prefix has a higher weight, yet when she talks it doesn't use the prefix.  She still gets the permissions, however.

**Comment by OllieMartin** [comment]
Hey, I have done a lot of digging through git repos and my own code and I cannot see anything that would cause this issue other than if in LuckPerms for some reason it doesnt add those temporary groups to whatever is queried by vault. I will keep looking but in the mean time I would try and contact Luck again if I were you to see if he can help. I know he said previously that it was not LuckPerms but I cannot see any other explanation.

If you do contact him tell him exactly the issue with that screenshot you just sent me of the groups and say that my plugin literally just queries the prefix from vault, so could it be possible that LuckPerms is not updating vault with the temporary higher weight prefix correctly?

Sorry for all the hassle, as I said I will keep looking in case I find anything :)

**Comment by dukedase** [comment]
Hey, I forgot to update you but I have fixed the issue.  It wasn't an issue with MultiChat, but it only happened when MultiChat was installed, which.. was really weird.  But it is fixed!

As for the only problem I think that remains, the permissions not updating, I think that may have fixed itself or something, because it doesn't seem to be happening anymore!  I assume the prefix thing is still around, but that is easily fixable by simplifying adding another color code after the space.

Thanks for being an awesome contributor, feel free to close this if you feel it is resolved.

**Comment by OllieMartin** [comment]
Fantastic I'm glad everything has worked out for you! Thanks for the patience as well through all this!

If you ever need anything else just let me know, thanks!
~ Ollie
