### ISSUE TITLE
AFK support

### ISSUE THREAD

**Issue by kencinder** [MultiChat/Development#53]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

If possible I would like to see AFK support added. Currently using Nucleus AFK on a Sponge server, but that doesn't support showing AFK across servers or nicknames provided by MultiChat for obvious reasons.
I know it's getting a little away from what is probably considered a "Chat" feature, but it does get posted to chat and notifies other players as such.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by OllieMartin** [comment]
Apologies for the slow reply, I will attatch the message I sent in Discord at the bottom which explains my absence.

This is something that I can look into, but unfortunately I have very little free time at the moment! Like you said, it is stretching the purpose of the plugin a bit, and it is hard to implement over bungeecord. But nethertheless, I will make sure its on my list of possibilities! :)

"Hello @everyone. I'm sure many of you are used to these sort of posts from me now... Firstly, you have my genuine apology for being absent for so long. I have started my new job only recently, and it has been hectic to say the least. I have had absolutely no free time whatsoever to dedicate to the plugin as much as I wish I had. I know a lot of you have been complaining about slow response times, and that the spigot page says "use Discord for fast support!", so again I am sorry that was not the case. However, I would like to extend a huge thanks to those of you in the community who have stepped up and helped everyone out when they needed it. Occasionally I would see notifications relevant to the plugin but just have no time to even look at it properly, but it reassuring to also see notifications answering peoples problems, so again thank you so much for 'holding the deck' so to say.

I am still extremely busy... However, I have slightly more time than before. I am going to aim to spend some time on the plugin in the next few weeks, and I am hoping I will be able to keep up with the support requests from you all here. It would be impossible for me to go through and answer every message that has been said while I have been away, so if you do have any issues please just send them again to the #support channel. I will get back to you ASAP :)

As far as I know the plugin is still in full working order with the current MC version, if it is not then I will try to get this fixed ASAP. I cannot commit to providing lots of new feaures currently because of how busy I am, but I will certainly ensure that the current features are working.

Thank you all for using the plugin as usual, and apologies for the lack of support."
