### ISSUE TITLE
Local is same as Global - unlimited range

### ISSUE THREAD

**Issue by Yorkforce** [MultiChat/Development#55]
**Describe the bug**
Players using local chat will show for everyone on the server regardless of how far away they are

**To Reproduce**
Move into local channel via /local
chat

**Expected behavior**
There should be a limited range on local chat, preferably a configurable setting. 

**Platform and Versions (please complete the following information):**
 - OS: Debian 8
 - Java Version: Java 8
 - MultiChat Version: 1.7.3
 - Proxy Version: Bungeecord-1402
 - Local Server Version: SpongeForge 3680

**Comment by kencinder** [comment]
I don't think this is the purpose of local chat. Global is across all servers, local is local to the server you are on.
That said I see nothing wrong with a setting for this if it's wanted, or even another channel that can be forced for distance.

**Comment by Yorkforce** [comment]
Sorry I understand the difference now, in other chat plugins local chat has always been a range thing which is where my confusion is coming from.

Come to think of it, a server only trade channel would actually be useful but a distance channel would also be very useful, especially for skyblock type modpacks where people chat to thier friends on islands in close proximity.

Would it be possible to have another default channel for range with a config option to set the distance?

**Comment by OllieMartin** [comment]
Hi there. Apologies for the slow reply, I will attatch the message I sent in Discord at the bottom which explains my absence.

MultiChat does not explicitly have this feature, however it is possible to do this by using a separate plugin to control your local chat such as essentials. If players go into /local mode with multichat, and essentials is set up to use a radius, then this will still work! Please let me know if you have any issues :)

"Hello @everyone. I'm sure many of you are used to these sort of posts from me now... Firstly, you have my genuine apology for being absent for so long. I have started my new job only recently, and it has been hectic to say the least. I have had absolutely no free time whatsoever to dedicate to the plugin as much as I wish I had. I know a lot of you have been complaining about slow response times, and that the spigot page says "use Discord for fast support!", so again I am sorry that was not the case. However, I would like to extend a huge thanks to those of you in the community who have stepped up and helped everyone out when they needed it. Occasionally I would see notifications relevant to the plugin but just have no time to even look at it properly, but it reassuring to also see notifications answering peoples problems, so again thank you so much for 'holding the deck' so to say.

I am still extremely busy... However, I have slightly more time than before. I am going to aim to spend some time on the plugin in the next few weeks, and I am hoping I will be able to keep up with the support requests from you all here. It would be impossible for me to go through and answer every message that has been said while I have been away, so if you do have any issues please just send them again to the #support channel. I will get back to you ASAP :)

As far as I know the plugin is still in full working order with the current MC version, if it is not then I will try to get this fixed ASAP. I cannot commit to providing lots of new feaures currently because of how busy I am, but I will certainly ensure that the current features are working.

Thank you all for using the plugin as usual, and apologies for the lack of support."
