### ISSUE TITLE
Permissions for using special caracters in nickname

### ISSUE THREAD

**Issue by thunderlight411** [MultiChat/Development#56]
Usage of special characters in nickname is possible without the permission "multichatspigot.nick.special"

**Platform and Versions (please complete the following information):**
 - OS: CentOS
 - Java Version: Java 8
 - MultiChat Version: [1.7.4
 - Proxy Version: Bungeecord-1413
 - Local Server Version: Paper-624

**Comment by thunderlight411** [comment]
@OllieMartin Any idea when you have time to fix this?

Its really annoying that players can use special characters in there nickname

**Comment by OllieMartin** [comment]
Hi there, Apologies for the slow reply, I will attatch the message I sent in Discord at the bottom which explains my absence.

I cannot recreate this issue! If I negate the multichatspigot.nick.special permission for me when I am online it prevents me using any kind of characters like !, #, . etc.

If you have any screenshots etc. of this happening, or your console log, please make a new issue and I will get to it ASAP! Many thanks :) And apologies again for the awful response time!

"Hello @everyone. I'm sure many of you are used to these sort of posts from me now... Firstly, you have my genuine apology for being absent for so long. I have started my new job only recently, and it has been hectic to say the least. I have had absolutely no free time whatsoever to dedicate to the plugin as much as I wish I had. I know a lot of you have been complaining about slow response times, and that the spigot page says "use Discord for fast support!", so again I am sorry that was not the case. However, I would like to extend a huge thanks to those of you in the community who have stepped up and helped everyone out when they needed it. Occasionally I would see notifications relevant to the plugin but just have no time to even look at it properly, but it reassuring to also see notifications answering peoples problems, so again thank you so much for 'holding the deck' so to say.

I am still extremely busy... However, I have slightly more time than before. I am going to aim to spend some time on the plugin in the next few weeks, and I am hoping I will be able to keep up with the support requests from you all here. It would be impossible for me to go through and answer every message that has been said while I have been away, so if you do have any issues please just send them again to the #support channel. I will get back to you ASAP :)

As far as I know the plugin is still in full working order with the current MC version, if it is not then I will try to get this fixed ASAP. I cannot commit to providing lots of new feaures currently because of how busy I am, but I will certainly ensure that the current features are working.

Thank you all for using the plugin as usual, and apologies for the lack of support."
