### ISSUE TITLE
critical exception - profanity chat control

### ISSUE THREAD

**Issue by Yorkforce** [MultiChat/Development#57]
**Describe the bug**
Our chat control is having problems filtering profanities, we have this entry in the config:

`- look_for: 'fuck|fck|fuk|shit|sex|cunt|twat|bastard|piss|wank|retard|rape|dick|gay|bitch|asshole|blowjob|penis|dildo|cancer|lesbian|whore|cock|wtf|mofo|omfg|ffs|retard|homo'`

**Full startup log of affected servers**
https://pastebin.com/Nz6Umr7y
Paste the FULL startup log of Bungeecord / Spigot here depending on where the issue occurs
```

**To Reproduce**
Steps to reproduce the behavior:
1. Player types profinity listed in above config
2. Console error occurs
3. Profanity is relayed to chat for all to see

**Expected behavior**
Profanity message should be cancelled and warning issues to player

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform and Versions (please complete the following information):**
 - OS: Debian 9 [e.g. Windows 10]
 - Java Version: 8 [e.g. Java 8]
 - MultiChat Version: 1.7.3 [e.g. 1.5.2]
 - Proxy Version: [e.g. Bungeecord-1523, Waterfall-156]
 - Local Server Version: spongeforge-1.12.2-2825-7.1.6  [e.g. craftbukkit234, spigot-1256, paperclip-456, spongevanilla-2456]

**Additional context**
Add any other context about the problem here.

**Comment by OllieMartin** [comment]
Hi there, apologies for the insanely slow reply, I will attach below the message I sent in Discord which explains my absence.

Thank you for your report! This was in fact an issue with spongeforge and I have just spent a while trying to fix it! It is now fixed and will ship in version 1.7.5 which I will release soon :)

Again my apologies for the wait!

"Hello @everyone. I'm sure many of you are used to these sort of posts from me now... Firstly, you have my genuine apology for being absent for so long. I have started my new job only recently, and it has been hectic to say the least. I have had absolutely no free time whatsoever to dedicate to the plugin as much as I wish I had. I know a lot of you have been complaining about slow response times, and that the spigot page says "use Discord for fast support!", so again I am sorry that was not the case. However, I would like to extend a huge thanks to those of you in the community who have stepped up and helped everyone out when they needed it. Occasionally I would see notifications relevant to the plugin but just have no time to even look at it properly, but it reassuring to also see notifications answering peoples problems, so again thank you so much for 'holding the deck' so to say.

I am still extremely busy... However, I have slightly more time than before. I am going to aim to spend some time on the plugin in the next few weeks, and I am hoping I will be able to keep up with the support requests from you all here. It would be impossible for me to go through and answer every message that has been said while I have been away, so if you do have any issues please just send them again to the #support channel. I will get back to you ASAP :)

As far as I know the plugin is still in full working order with the current MC version, if it is not then I will try to get this fixed ASAP. I cannot commit to providing lots of new feaures currently because of how busy I am, but I will certainly ensure that the current features are working.

Thank you all for using the plugin as usual, and apologies for the lack of support."
