### ISSUE TITLE
staff chats not working

### ISSUE THREAD

**Issue by FarmerMisShelley** [MultiChat/Development#58]
i've set the perms and everything and none of my staff are able to do /mc and /ac. even me, owner can't. it keeps saying "unknown command". help pls?

**Comment by OllieMartin** [comment]
Hi there, apologies for the very long wait for a response, I will attach my message from Discord at the end which explains my absence.

It sounds to me like you have not installed MultiChat on bungeecord, and instead on Spigot. If this is still an issue please open a new ticket :)

"Hello @everyone. I'm sure many of you are used to these sort of posts from me now... Firstly, you have my genuine apology for being absent for so long. I have started my new job only recently, and it has been hectic to say the least. I have had absolutely no free time whatsoever to dedicate to the plugin as much as I wish I had. I know a lot of you have been complaining about slow response times, and that the spigot page says "use Discord for fast support!", so again I am sorry that was not the case. However, I would like to extend a huge thanks to those of you in the community who have stepped up and helped everyone out when they needed it. Occasionally I would see notifications relevant to the plugin but just have no time to even look at it properly, but it reassuring to also see notifications answering peoples problems, so again thank you so much for 'holding the deck' so to say.

I am still extremely busy... However, I have slightly more time than before. I am going to aim to spend some time on the plugin in the next few weeks, and I am hoping I will be able to keep up with the support requests from you all here. It would be impossible for me to go through and answer every message that has been said while I have been away, so if you do have any issues please just send them again to the #support channel. I will get back to you ASAP :)

As far as I know the plugin is still in full working order with the current MC version, if it is not then I will try to get this fixed ASAP. I cannot commit to providing lots of new feaures currently because of how busy I am, but I will certainly ensure that the current features are working.

Thank you all for using the plugin as usual, and apologies for the lack of support."
