### ISSUE TITLE
[sponge] color not working

### ISSUE THREAD

**Issue by Kxnrl** [MultiChat/Development#87]
**Describe the bug**
color not working

**Full startup log of affected servers**
```
override_global_format_format: "&7[%SERVER%] &c[&9%luckperms_primary_group_name%&c] &r&a%DISPLAYNAME%&f: "
```

**To Reproduce**
install placeholderapi.
install multichat
change format and use luckperms_primary_group_name

**Expected behavior**
if use space split, that will work

**Screenshots**
![image](https://user-images.githubusercontent.com/3905845/79054828-b9022000-7c7a-11ea-8f67-650176872166.png)

**Platform and Versions (please complete the following information):**
 - OS: windows server 2016
 - Java Version: JAVA 8
 - MultiChat Version:  latest
 - Proxy Version: waterfall-latest
 - Local Server Version: spongeforge-1.12.2

**Comment by OllieMartin** [comment]
Hi there,

This seems very strange the colour code isn’t being applied. Does this now work for any of your ranks? Did you say that if you leave a space then it does in fact work? 

Is there also a reason you aren’t using in the built in %PREFIX% placeholder and using LuckPerms to set your prefixes?

Sorry for lots of questions, I just hope to help you figure out what the issue is!

**Comment by Kxnrl** [comment]
```
override_global_format_format: "&7[%SERVER%] &c[&9 %luckperms_primary_group_name%&c] &r&a%DISPLAYNAME%&f: "
```
this will work.

where I can find the built-in %PREFIX% placeholders? I checked all wiki docs.

**Comment by Kxnrl** [comment]
sorry, I am new for minecraft

**Comment by Kxnrl** [comment]
and this format works fine on my spigot lobby server.

**Comment by OllieMartin** [comment]
You can try using %PREFIX% instead of %luckperms_primary_group%. Then that will use whatever prefix you set with luckperms. It is strange that the color code you have set doesn’t seem to be working though.

I will investigate further! But try %PREFIX% and see if that helps

**Comment by Kxnrl** [comment]
%luckperms_primary_group% works with newhonor plugins. 
I will try %PREFIX% later.

**Comment by OllieMartin** [comment]
Hi, I have done some experimenting! It turns out this is actually an issue with PAPI on Sponge as a whole. You can check for yourself by running this kind of command: /papi parse Revilo410 &2[&4%player%

Basically, for some reason, placeholder API deletes any colour codes directly attached to the front of their placeholders! I do not know if this is intended or not, but it is an issue with their plugin.

You can however avoid the issue because MultiChat provides its own %PREFIX% placeholder which gets whatever prefix you set in LuckPerms. So if you use luckperms to set the prefix for your rank, for example set Owner's prefix to be &c[&9Owner&c]. Then MultiChat will get this using the %PREFIX% placeholder. :)

Let me know if there is anything else I can do!
