### ISSUE TITLE
plugin does not respect /sponge plugins reload | no plugin reload command for sponge

### ISSUE THREAD

**Issue by codydbgt** [MultiChat/Development#94]
doing 

> /sponge plugins reload

will not reload the config infact there is no way to reload the config in sponge 
also the config is placed in the root game dir not its own folder

**Comment by OllieMartin** [comment]
Hi there,

MultiChat on Sponge already has a reload command in the development builds, it just has not been released quite yet. The config has also been moved to the correct place in the development builds too.

The reason it wasn't correct to start with is because the Sponge version of MultiChat used to be very limited, but it now has slowly had more functions added to it, and as of the next version will be fully functional with the reload command etc.

I actually wasn't aware of the /Sponge plugins reload command before, but I might be able to implement this as well to call the pre-existing reload command.

I will sort it out for you ready for the next version, hope that helps.

**Comment by OllieMartin** [comment]
This has been fully added in the development builds and will hopefully be released very soon :)
